#!/usr/bin/env python3
"""Initialize the HW02 NE 630 solution table from typeset submissions."""

from __future__ import annotations

import match_hw04_latex as core


core.HOMEWORK_ID = "hw02"
core.HW_DIR = core.ROOT / "hw02"
core.TABLE_DIR = core.HW_DIR / "tables"
core.ARTIFACT_DIR = core.HW_DIR / "table_artifacts"
core.PDF_TEXT_DIR = core.ARTIFACT_DIR / "pdf_text"
core.STATEMENT_PATH = str(core.NE630_ROOT / "homework/markdown/HW02.md")
core.SOLUTION_PATH = str(core.NE630_ROOT / "homework/solutions/hw02.tex")

core.SPECS = (
    core.AnswerSpec(
        "p01",
        "a",
        "decay_heat_1day_1yr_operation",
        "Problem 1(a) decay heat 1 day after 1 year operation",
        4.44,
        "MW",
        "4.44 MW",
        0.25,
        r"P_d(86400) \approx \boxed{4.44~\mathrm{MW}}",
        (r"Final\s+(?:answer|Result)\s*\(a\)", r"1\s*day[^\n]{0,80}(?:MW|mega)", r"4\.4[0-9]"),
        ("day", "MW", "4."),
        2.0,
        7.0,
    ),
    core.AnswerSpec(
        "p01",
        "b",
        "decay_heat_1month_1yr_operation",
        "Problem 1(b) decay heat 1 month after 1 year operation",
        1.31,
        "MW",
        "1.31 MW",
        0.15,
        r"P_d(2592000) \approx \boxed{1.31~\mathrm{MW}}",
        (r"Final\s+(?:answer|Result)\s*\(b\)", r"1\s*month[^\n]{0,80}(?:MW|mega)", r"1\.3[0-9]"),
        ("month", "MW", "1."),
        0.5,
        2.2,
    ),
    core.AnswerSpec(
        "p01",
        "c",
        "decay_heat_1year_1yr_operation",
        "Problem 1(c) decay heat 1 year after 1 year operation",
        0.255,
        "MW",
        "0.255 MW",
        0.05,
        r"P_d(31536000) \approx \boxed{0.255~\mathrm{MW}}",
        (r"Final\s+(?:answer|Result)\s*\(c\)", r"1\s*year[^\n]{0,80}(?:MW|mega)", r"0\.25[0-9]"),
        ("year", "MW", "0."),
        0.05,
        0.7,
    ),
    core.AnswerSpec(
        "p01",
        "d",
        "decay_heat_1day_1month_operation",
        "Problem 1(d) one-month operation, 1 day after shutdown",
        3.182,
        "MW",
        "3.182 MW",
        0.25,
        r"P_d(86400;t_0=1~\mathrm{month}) \approx \boxed{3.182~\mathrm{MW}}",
        (r"one\s+month[^\n]{0,160}1\s*day", r"3\.18[0-9]"),
        ("month", "day", "MW", "3."),
        1.0,
        5.0,
    ),
    core.AnswerSpec(
        "p01",
        "d",
        "decay_heat_1month_1month_operation",
        "Problem 1(d) one-month operation, 1 month after shutdown",
        0.420,
        "MW",
        "0.420 MW",
        0.08,
        r"P_d(2592000;t_0=1~\mathrm{month}) \approx \boxed{0.420~\mathrm{MW}}",
        (r"one\s+month[^\n]{0,200}0\.42", r"0\.42[0-9]"),
        ("month", "MW", "0.4"),
        0.1,
        0.9,
    ),
    core.AnswerSpec(
        "p01",
        "d",
        "decay_heat_1year_1month_operation",
        "Problem 1(d) one-month operation, 1 year after shutdown",
        0.031,
        "MW",
        "0.031 MW",
        0.015,
        r"P_d(31536000;t_0=1~\mathrm{month}) \approx \boxed{0.031~\mathrm{MW}}",
        (r"one\s+month[^\n]{0,240}0\.031", r"0\.031"),
        ("year", "MW", "0.03"),
        0.005,
        0.12,
    ),
    core.AnswerSpec(
        "p02",
        "a",
        "representative_channel_q_value",
        "Problem 2(a) representative fission-channel Q value",
        185.74,
        "MeV",
        "185.74 MeV for Sr-96/Xe-138 + 2n",
        30.0,
        r"Q \approx \boxed{185.74~\mathrm{MeV}}",
        (r"Q\s*(?:=|≈)[^\n]{0,120}(?:MeV)", r"Q\s+value[^\n]{0,120}(?:MeV)"),
        ("Q", "MeV"),
        140.0,
        230.0,
    ),
    core.AnswerSpec(
        "p03",
        "d",
        "exact_power_rise_time",
        "Problem 3(d) exact power-rise time",
        4.7235e-4,
        "s",
        "4.7235e-4 s",
        5.0e-5,
        r"t_{\mathrm{exact}}\approx\boxed{4.7235\times10^{-4}~\mathrm{s}}",
        (r"exact[^\n]{0,120}(?:10|s|ms)", r"t[_ ]?exact[^\n]{0,120}(?:10|s|ms)"),
        ("exact", "s", "10"),
        1.0e-4,
        1.0e-3,
    ),
    core.AnswerSpec(
        "p03",
        "d",
        "approx_power_rise_time",
        "Problem 3(d) approximate power-rise time",
        4.70e-4,
        "s",
        "4.70e-4 s",
        5.0e-5,
        r"t_{\mathrm{approx}}\approx\boxed{4.7000\times10^{-4}~\mathrm{s}}",
        (r"approx[^\n]{0,120}(?:10|s|ms)", r"t[_ ]?approx[^\n]{0,120}(?:10|s|ms)"),
        ("approx", "s", "10"),
        1.0e-4,
        1.0e-3,
    ),
)

core.TEXT_SPECS = (
    core.TextSpec(
        "p02",
        "a",
        "representative_fission_channel",
        "Problem 2(a) complete representative fission reaction",
        "algebraic",
        r"^{235}U+n\rightarrow{}^{96}Sr+{}^{138}Xe+2n",
        r"\isoA{U}{235}+n \rightarrow \isoA{Sr}{96}+\isoA{Xe}{138}+2n",
    ),
    core.TextSpec(
        "p02",
        "b",
        "fragment_n_to_z_comparison",
        "Problem 2(b) N/Z comparison with stable isobars",
        "short_answer",
        "The selected fission products have larger neutron-to-proton ratios than stable isobars with the same mass numbers.",
        "Both fission products therefore have larger neutron-to-proton ratios than the corresponding stable isobars.",
        ("compare each fragment N/Z to a stable isobar", "identify neutron-rich products"),
    ),
    core.TextSpec(
        "p02",
        "c",
        "why_neutron_rich",
        "Problem 2(c) reason fission fragments are neutron rich",
        "short_answer",
        "The heavy compound nucleus has excess neutrons and scission is too fast for fragments to move directly to the valley of stability.",
        "The compound nucleus contains substantially more neutrons than protons... residual fragments generally remain neutron rich.",
        ("heavy fissile nucleus has high N/Z", "prompt neutrons do not remove all excess"),
    ),
    core.TextSpec(
        "p02",
        "d",
        "principal_decay_mode",
        "Problem 2(d) principal decay mode toward stability",
        "short_answer",
        "Neutron-rich fragments principally beta-minus decay, increasing Z by one and reducing N/Z toward stability.",
        "The principal decay mode of both selected fragments is beta-minus decay.",
        ("beta-minus decay", "moves products toward stability"),
    ),
    core.TextSpec(
        "p02",
        "e",
        "prompt_delayed_particles_unrecoverable_energy",
        "Problem 2(e) prompt/delayed emissions and unrecoverable energy",
        "short_answer",
        "Prompt fission emits fragments, prompt neutrons, and prompt gammas; later decays emit betas, antineutrinos, gammas, and sometimes delayed neutrons. Antineutrino energy is effectively unrecoverable.",
        "The antineutrinos interact so weakly that their energy is effectively unrecoverable for power production.",
        ("prompt neutrons/gammas", "beta and gamma decay", "antineutrino energy unrecoverable"),
    ),
    core.TextSpec(
        "p03",
        "a",
        "chain_generation_exact",
        "Problem 3(a) exact generation expression",
        "algebraic",
        r"n(t)=n_0 k^{t/\ell}",
        r"\boxed{n(t)=n_0k^{t/\ell}}",
    ),
    core.TextSpec(
        "p03",
        "b",
        "chain_generation_exponential_approx",
        "Problem 3(b) exponential approximation",
        "algebraic",
        r"n(t)\approx n_0\exp((k-1)t/\ell)",
        r"\boxed{n(t)\approx n_0\exp((k-1)t/\ell)}",
    ),
    core.TextSpec(
        "p03",
        "c",
        "criticality_classification",
        "Problem 3(c) k classifications",
        "short_answer",
        "k=0.995 is subcritical and decreases, k=1.000 is critical and steady, k=1.005 is supercritical and grows.",
        "k=0.995 subcritical; k=1.000 critical; k=1.005 supercritical.",
        ("subcritical", "critical", "supercritical", "long-term behavior"),
    ),
)


if __name__ == "__main__":
    core.main()
